import 'package:flutter/material.dart';
import 'package:viewpager_flutter/CreatedWidget/ContainersWidget_page2.dart';

import 'CreatedWidget/ContainersWidget_page1.dart';
import 'CreatedWidget/ContainersWidget_page3.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: "View pager flutter",
      home: Scaffold(
        appBar: AppBar(
          centerTitle: true,
          title: const Text(
            "View pager in flutter",
            style: TextStyle(color: Colors.amber),
          ),
        ),
        body: PageView(
          children: <Widget>[
            Container(
                child: SingleChildScrollView(
              padding: EdgeInsets.symmetric(horizontal: 20, vertical: 20),
              child: Column(
                children: [
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                  SizedBox(height: 20),
                  ContainersWidget1(),
                ],
              ),
            )),
            Container(
              child: Center(
                  child: SingleChildScrollView(
                padding: EdgeInsets.symmetric(horizontal: 20, vertical: 20),
                child: Column(
                  children: [
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                    SizedBox(height: 20),
                    ContainersWidget2(),
                  ],
                ),
              )),
            ),
            Container(
              child: Center(
                  child: SingleChildScrollView(
                padding: EdgeInsets.symmetric(horizontal: 20, vertical: 20),
                child: Column(
                  children: [
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                    SizedBox(height: 20),
                    ContainersWidget3(),
                  ],
                ),
              )),
            ),
          ],
        ),
      ),
    );
  }
}
